# Generated by Django 4.2 on 2023-04-21 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='task',
            name='finaldate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Vacation_rescheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada1_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada1_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada2_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada2_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación1_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación1_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación2_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación2_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación3_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_reprogramación3_hasta', models.DateTimeField(blank=True, null=True)),
                ('motivos_de_reprogramación', models.CharField(blank=True, max_length=200, null=True)),
                ('dias_habiles', models.IntegerField(blank=True, null=True)),
                ('justificación_de_la_reprogramación', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation_account_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada1', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada1_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada2', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada2_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada3', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitada3_hasta', models.DateTimeField(blank=True, null=True)),
                ('dias_habiles', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('justificación', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register_assistence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hora_ingreso_mañana', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hora_salida_mañana', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hora_ingreso_tarde', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hora_salida_tarde', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('constancy', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_leave_with_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensación', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_de_compensación', models.DateTimeField(blank=True, null=True)),
                ('compensación_desde_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('compensación_hasta_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('fecha_de_salida', models.DateTimeField(blank=True, null=True)),
                ('salida_desde_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('salida_hasta_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Official_permit_for_hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisión', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_de_la_comisión', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_de_salida', models.DateTimeField(blank=True, null=True)),
                ('desde_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('hasta_hora', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('a_paterno', models.CharField(blank=True, max_length=15, null=True)),
                ('a_materno', models.CharField(blank=True, max_length=15, null=True)),
                ('reparticion', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('detail', models.TextField(max_length=1000)),
                ('finaldate', models.DateTimeField(blank=True, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
