# Generated by Django 4.1 on 2023-04-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_description_task_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_permit_for_hours',
            name='aprobacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='personal_leave_with_pay',
            name='aprobacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='register_assistence',
            name='aprobacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vacation_account_request',
            name='aprobacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='aprobacion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
