# Generated by Django 4.1 on 2023-04-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_official_permit_for_hours_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_permit_for_hours',
            name='dateapproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal_leave_with_pay',
            name='dateapproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register_assistence',
            name='dateapproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation_account_request',
            name='dateapproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation_rescheduling',
            name='dateapproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
