# Generated by Django 4.1 on 2023-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_official_permit_for_hours_dateapproved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_user',
            name='dias_de_vacacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_user',
            name='fecha_de_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
