# Generated by Django 4.1 on 2023-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_data_user_dias_de_vacacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horas_laborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_mañana', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('salida_mañana', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('ingreso_tarde', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
                ('salida_tarde', models.TimeField(blank=True, null=True, verbose_name='Hora del día')),
            ],
        ),
    ]
