# Generated by Django 4.1 on 2023-04-26 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_horas_laborales'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_user',
            name='fecha_en_que_se_asigno_vacacion',
            field=models.DateTimeField(default=datetime.date(2000, 1, 1)),
        ),
    ]
