# Generated by Django 4.1 on 2023-04-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_data_user_fecha_en_que_se_asigno_vacacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_user',
            name='dias_de_vacacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
