# Generated by Django 4.2 on 2023-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_data_user_dias_de_vacacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official_permit_for_hours',
            old_name='desde_hora',
            new_name='desde_hora_m',
        ),
        migrations.RenameField(
            model_name='official_permit_for_hours',
            old_name='hasta_hora',
            new_name='desde_hora_t',
        ),
        migrations.AddField(
            model_name='data_user',
            name='horas_con_goce_de_haberes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='official_permit_for_hours',
            name='hasta_hora_m',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del día'),
        ),
        migrations.AddField(
            model_name='official_permit_for_hours',
            name='hasta_hora_t',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del día'),
        ),
        migrations.AddField(
            model_name='official_permit_for_hours',
            name='horas_de_permiso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
