# Generated by Django 4.1 on 2023-04-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_desde_hora_official_permit_for_hours_desde_hora_m_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official_permit_for_hours',
            old_name='horas_asignadas',
            new_name='horas_de_permiso',
        ),
    ]
