# Generated by Django 4.1 on 2023-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_official_permit_for_hours_horas_de_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official_permit_for_hours',
            name='horas_de_permiso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
