# Generated by Django 4.1 on 2023-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_official_permit_for_hours_horas_de_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_user',
            name='horas_con_goce_de_haberes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
