# Generated by Django 4.1 on 2023-04-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_data_user_horas_con_goce_de_haberes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_leave_with_pay',
            old_name='salida_desde_hora',
            new_name='salida_desde_hora_m',
        ),
        migrations.RenameField(
            model_name='personal_leave_with_pay',
            old_name='salida_hasta_hora',
            new_name='salida_desde_hora_t',
        ),
        migrations.AddField(
            model_name='personal_leave_with_pay',
            name='salida_hasta_hora_m',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del día'),
        ),
        migrations.AddField(
            model_name='personal_leave_with_pay',
            name='salida_hasta_hora_t',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del día'),
        ),
    ]
