# Generated by Django 4.1 on 2023-04-27 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_rename_salida_desde_hora_personal_leave_with_pay_salida_desde_hora_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_user',
            name='fecha_en_que_se_asigno_dias_goce',
            field=models.DateTimeField(default=datetime.date(2000, 1, 1)),
        ),
    ]
