# Generated by Django 4.1 on 2023-04-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_data_user_fecha_en_que_se_asigno_dias_goce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_user',
            name='dias_de_vacacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
