# Generated by Django 4.1 on 2023-04-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_data_user_dias_de_vacacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation_account_request',
            name='motivo',
        ),
    ]
