# Generated by Django 4.1 on 2023-04-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_vacation_account_request_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation_account_request',
            name='dias_habiles',
        ),
        migrations.AddField(
            model_name='vacation_account_request',
            name='dias_habiles_programados',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
