# Generated by Django 4.1 on 2023-05-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_desde_hora_official_permit_for_hours_desde_hora_m_and_more'),
        ('tasks', '0020_remove_vacation_account_request_dias_habiles_and_more'),
    ]

    operations = [
    ]
